title: Yung Xuan's projects
description: Welcome to my personal webpage, where I showcase a collection of projects that highlight my skills and expertise in the data field.
show_downloads: false
google_analytics:
theme: jekyll-theme-slate

projects:
  - title: "NBA MVP Prediction"
    description: "My Diploma's FYP aimed at predicting the NBA's Most Valuable Player (MVP) based on player statistics, team performance, and historical data"
    repo_link: "https://github.com/yungxuan819/NBA_MVP_Prediction_FYP"
  - title: "Student Performance Analysis"
    description: "To understand the influence of the parents background, test preparation etc on students' academic performances, and accurately predict students' performance (score)"
    repo_link: "https://github.com/yungxuan819/student_performance_analysis"
  - title: "House Price Analysis"
    description: "A project focused on identifying key factors that influence house prices, and accurately predict house prices based on these factors"
    repo_link: "https://github.com/yungxuan819/Bengaluru_House_Price_Prediction"
  - title: "Music Popularity Prediction"
    description: "Based on pre-collected Spotify API data, I analyzed and find out the best predictive model to accurately predict the popularity index for each track"
    repo_link: "https://github.com/yungxuan819/music_popularity_prediction"
  - title: "Heart Disease Analysis"
    description: "I analyzed a dataset of individuals at high or low risk for heart problems using visualizations, and built predictive models to determine the most effective classification method for this case"
    repo_link: "https://github.com/yungxuan819/heart-disease-analysis"
  - title: "YouTube Channels Analysis"
    description: "This project involves analyzing a dataset containing key statistics from various YouTube channels, including views, subscribers, total videos, and more. The focus is on performing EDA through impactful visualizations, alongside with data cleaning and predictive model building to predict the 'average_views' of each channel."
    repo_link: "https://github.com/yungxuan819/youtube_channels_analysis"
  - title: "Data Analysis Web App using Streamlit"
    description: "This project is a Data Analysis Web App built with Streamlit and Python. It allows users to upload CSV datasets and perform basic data analysis and visualizations without needing any coding knowledge. The app provides various interactive features to help users explore their datasets, identify missing values, and visualize key insights."
    repo_link: "https://github.com/yungxuan819/data-analysis-web-app"
    app_link: "https://yxdataanalysiswebapp.streamlit.app/"
